FROM rust:alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM alpine:3
RUN apk add --no-cache git
COPY --from=builder /src/target/release/zit /usr/local/bin/zit
